"""
Offline pipeline of the diet project (E0/E1 normalisation, E2 load and embedding, rotation analysis).

Reads the frozen dataset (tag ``dataset-v1``) and produces the canonical food catalogue and the structured diet items.
Depends only on the standard library and on the shared ``finalprosports.domain`` package (pure Python). Every script fails
loudly when an input is missing and is idempotent. The dataset lives OUTSIDE the code tree: it is located through
``FPS_DATASET_DIR`` / ``FPS_DATA_DIR`` (environment or ``.env`` at the repository root, see ``pipeline.paths``); no path into
the data tree is written in code.
"""
from __future__ import annotations

import sys
from pathlib import Path

from pipeline.paths import backend_src, data_dir, dataset_dir, docs_dir, repo_root  # noqa: F401

SRC_DIR = Path(__file__).resolve().parents[1]            # pipeline/src/
REPO_ROOT = repo_root()                                  # TFM/code
DATA_DIR = Path(__file__).resolve().parent / "data"      # human-criterion JSON (synonyms, attributes, exclusions, brands)
DATASET_DIR = dataset_dir()                              # frozen dataset (FPS_DATASET_DIR)
PRIVATE_DIR = DATASET_DIR / "_private"
DOCS_DIR = docs_dir()                                    # versioned reports regenerated by the pipeline (docs/data)

for _p in (SRC_DIR, backend_src()):                      # make `import pipeline` / `import finalprosports` work without installation
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))
