import re
from dataclasses import dataclass

from .goal import Goal
from .restriction import Restriction

CORPUS_CODE_RE = re.compile(r"^CLIENTE_\d{3}$")          # pseudonyms of the case base (dataset-v1)
PORTFOLIO_KEY_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", re.I)   # UUID assigned by the application


def is_corpus_code(value: str) -> bool:
    return bool(CORPUS_CODE_RE.match(value or ""))


def is_portfolio_key(value: str) -> bool:
    return bool(PORTFOLIO_KEY_RE.match(value or ""))


@dataclass(frozen=True)
class ClientProfile:
    """What the ENGINE knows about a person: no name, health only as booleans/structured restrictions.

    Two populations share the type: the CASE BASE (``is_corpus_case`` True: the corpus, used by retrieval and never exposed as a
    client) and the PORTFOLIO of the professional (``is_corpus_case`` False: what the application lists, edits and prescribes for).
    The separation is a data-treatment decision (S1), enforced in the repository, not a UI detail.

    ``client_code`` is the INTERNAL KEY, never an identity shown to a person (S9): for a case of the corpus it is the
    pseudonym ``CLIENTE_NNN`` that dataset-v1 assigned; for a client of the portfolio it is a UUID generated by the application
    at registration. The identity of a portfolio client (name, birth date, phone, e-mail) lives in the RECORD (``ClientRecord.
    identification``) and never travels with the profile, so the engine, the evidence and the saved payloads never carry a name."""

    client_code: str
    professional_id: str
    sex: str | None                       # 'M' | 'F' | None
    age: int | None
    height_cm: int | None
    activity_level: int | None
    goal: Goal | None = None
    has_allergies: bool = False
    has_intolerances: bool = False
    has_medical_restrictions: bool = False
    restrictions: tuple[Restriction, ...] = ()
    is_athlete: bool | None = None
    is_corpus_case: bool = False           # S1: True = pseudonymous case of the corpus (retrieval only); False = client of the professional's portfolio
    sport: str | None = None
    corpus_alias: str | None = None
    """El seudónimo con el que ESTE cliente figura en la base de casos, cuando es la misma persona.

    La cartera identifica por UUID y el corpus por `CLIENTE_NNN`, y no había puente entre los dos. Un cliente que ya
    era caso del profesional antes de existir la aplicación está en los dos sitios con dos códigos distintos, así que
    la exclusión obligatoria por `client_code` no lo protegía: el sistema podía devolverle SU PROPIA dieta como caso de
    un tercero. Se confirmó con un cliente real, cuyas dos dietas están en el corpus con J = 1,0000.

    Lo DECLARA el profesional, que es quien sabe quién es quién; el sistema solo propone candidatos medidos
    (`data_tools/link_portfolio_to_corpus.py`) y nunca enlaza por su cuenta. La razón no es prudencia: es que el
    contenido NO identifica a una persona en este corpus. Hay 19 pares de dietas IDÉNTICAS (J = 1,0) entre clientes
    distintos, porque él reutiliza dietas literalmente. Lo único que resultó fiable es la unanimidad sobre el historial
    completo — todas las dietas del cliente con gemelo J >= 0,98 en el mismo seudónimo —, con 0 falsos enlaces sobre
    los 167 clientes del corpus que tienen dos o más dietas.
    """
    body_type: str | None = None          # complexión por muñeca declarada en el cuestionario (campo sucio: ver `body_type_policy`)
    training_time: str | None = None      # franja horaria de entrenamiento declarada en el cuestionario
    methods: tuple[str, ...] = ()         # régimen estructural de la DIETA (ayuno, cetosis, descarga)               # S3: algorithm input from the intake sheet (informative today; retrieval weights are goal/sex/age/activity/restrictions)
    disliked_food_ids: tuple[int, ...] = ()        # S3: «gustos negativos» resolved against the catalogue -> soft exclusions applied by the validator
    liked_food_ids: tuple[int, ...] = ()
    """Los «gustos positivos» resueltos contra el catálogo. Se extraían y no se usaban en ningún sitio.

    Entran porque está MEDIDO que él los tiene en cuenta: los alimentos que un cliente declara aparecen en sus dietas
    **+0,0643 [+0,0120, +0,1211]** por encima de la tasa base de ese mismo alimento en el mismo objetivo, sobre 169
    pares de 61 clientes. Y el control negativo sale como tiene que salir —los alimentos que el cliente rechaza
    aparecen **−0,0612 [−0,1093, −0,0110]** por debajo—, así que la mitad positiva es fiable.

    Cobertura: 61 de los 261 clientes con dietas (23,4 %), con 2,8 alimentos resueltos de media.

    Lo que NO son: una fuente de alimentos. Solo pueden DESEMPATAR entre candidatos que ya vienen de los casos
    recuperados (`composition_policy.compose_meals`), nunca introducir uno que el consenso no propusiera. Lo impone
    `tests/domain/test_likes_never_introduce_a_food.py`."""
    owned_supplement_ids: tuple[int, ...] = ()     # S3: supplements the client already has -> shown with the proposal, never vetoed

    # ------------------------------------------------------------------------------------ COMPOSICIÓN CORPORAL MEDIDA
    # La báscula conectada del profesional, no el cuestionario. Ocho magnitudes que él registra desde 2016 y que hasta
    # ahora no salían de `body_measurements`: la función de similitud miraba cinco números y ninguno era el cuerpo.
    #
    # `measured_at` NO es decorativo: es el sello que hace auditable la regla temporal. Un perfil solo puede llevar la
    # lectura MÁS RECIENTE ANTERIOR a la fecha de la dieta que se está prediciendo (`body_measurement_policy.as_of`,
    # comparación estricta). Sin el sello no se puede comprobar a posteriori que no hubo fuga, y con una serie que va
    # de 2016 a 2026 sobre los mismos clientes la fuga sería la explicación más probable de cualquier mejora.
    # Un perfil sin lectura utilizable deja los ocho campos a None y la similitud excluye el rasgo; nunca se imputa.
    weight_kg: float | None = None
    fat_pct: float | None = None
    muscle_mass_kg: float | None = None
    hydration_pct: float | None = None
    bone_mass_kg: float | None = None
    physique_rating: int | None = None
    visceral_fat_rating: float | None = None
    metabolic_age: int | None = None
    basal_met_kcal: int | None = None
    measured_at: str | None = None        # fecha ISO de la lectura usada; None = no se usó ninguna

    # ------------------------------------------------------------------------------------- MEDICIONES ANALÍTICAS
    # Resueltas por `lab_measurement_policy.as_of` a la fecha de la dieta: un valor por parámetro, el vigente ese día.
    # `lab_spans` es el recorrido observado de cada parámetro en el corpus, y hace falta para poder comparar dos
    # magnitudes cuyas escalas no tienen nada que ver. Los dos son diccionarios y no columnas: son 189 parámetros y
    # ninguno está en todos los clientes.
    #
    # NO salen en el documento del cliente. Lo impone `tests/architecture/test_labs_never_reach_the_client.py`.
    lab_values: dict[str, float] | None = None
    lab_spans: dict[str, float] | None = None

    @property
    def has_body_composition(self) -> bool:
        return self.weight_kg is not None or self.fat_pct is not None

    @property
    def age_bucket(self) -> str:
        if self.age is None:
            return "edad_NA"
        return "<25" if self.age < 25 else "25-39" if self.age < 40 else "40-54" if self.age < 55 else "55+"
